version: "3.10.10"

services:
  backend:
    build: .
    container_name: backend_todo
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./core:/app
    ports:
      - "7000:7000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        # Change the number before : to the port the web interface should be accessible on
        - '5000:70'
        # Change the number before : to the port the SMTP server should be accessible on
        - '25:25'
        # Change the number before : to the port the IMAP server should be accessible on
        - '143:143'
      volumes:
          - smtp4dev-data:/smtp4dev
      environment:
        - ServerOptions__Urls=http://*:70
        - ServerOptions__HostName=smtp4dev
volumes:
    smtp4dev-data: