version: "3.10.10"

services:
  backend:
    build: .
    container_name: backend_todo
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./core:/app
    ports:
      - "7000:7000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
