<<<<<<< Updated upstream
# Generated by Django 4.2.15 on 2024-08-29 22:24
=======
# Generated by Django 4.2.15 on 2024-10-10 08:28
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< Updated upstream
        ('todo', '0001_initial'),
=======
        ("todo", "0001_initial"),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AlterField(
<<<<<<< Updated upstream
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
>>>>>>> Stashed changes
        ),
    ]
