name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Run Test flake8
      run: docker-compose exec -T backend sh -c "flake8"

    - name: Run Test pytest
      run: docker-compose exec -T backend sh -c "pytest ."

